project:
  type: book
  output-dir: _book

book:
  title: "GPU-Accelerated Mathematical Illustration"
  subtitle: "An Introduction to Shader Programming"
  cover-image: images/cover.png

  chapters:
    - index.qmd
    - part: "Lectures"
      chapters:
        - lectures/day1/notes.qmd
        - lectures/day2/notes.qmd
        - lectures/day3/notes.qmd
        - lectures/day4/notes.qmd

  appendices:
    - lectures/day1/shaders.qmd
    - lectures/day2/shaders.qmd
    - lectures/day3/shaders.qmd
    - lectures/day4/shaders.qmd

format:
  pdf:
    pdf-engine: lualatex
    documentclass: scrbook
    fontfamily: libertinus
    fontsize: 10pt
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    fig-width: 5.25
    keep-tex: true
    callout-appearance: simple
    geometry:
      - letterpaper
      - left=1.5in
      - right=1.5in
      - top=1.25in
      - bottom=1.25in
    include-in-header: preamble.tex
