book:
  chapters:
    - index.qmd
    - part: "Lectures"
      chapters:
        - lectures/day1.qmd
        - lectures/day2.qmd
        - lectures/day3.qmd
    - part: "Slides"
      chapters:
        - slides/day1-slides.qmd
        - slides/day2-slides.qmd
        - slides/day3-slides.qmd

  appendices:
    - lectures/shaders/day1-shaders.qmd
    - lectures/shaders/day2-shaders.qmd
    - lectures/shaders/day3-shaders.qmd

  downloads: [pdf]

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    link-external-newwindow: true
    smooth-scroll: true
