project:
  type: website
  output-dir: _site

website:
  title: "GPU-Accelerated Mathematical Illustration"
  repo-url: https://github.com/stevejtrettel/shader-course

  sidebar:
    style: docked
    collapse-level: 2
    contents:
      - index.qmd
      - section: "Day 1: Introduction"
        contents:
          - text: "Notes"
            href: lectures/day1/notes.qmd
          - text: "Slides"
            href: lectures/day1/slides.html
          - text: "Code"
            href: lectures/day1/shaders.qmd
      - section: "Day 2: Dynamics"
        contents:
          - text: "Notes"
            href: lectures/day2/notes.qmd
          - text: "Slides"
            href: lectures/day2/slides.html
          - text: "Code"
            href: lectures/day2/shaders.qmd
      - section: "Day 3: Tilings"
        contents:
          - text: "Notes"
            href: lectures/day3/notes.qmd
          - text: "Slides"
            href: lectures/day3/slides.html
          - text: "Code"
            href: lectures/day3/shaders.qmd
      - section: "Day 4: Simulations"
        contents:
          - text: "Notes"
            href: lectures/day4/notes.qmd
          - text: "Slides"
            href: lectures/day4/slides.html
          - text: "Code"
            href: lectures/day4/shaders.qmd
      - section: "Day 5: Rendering"
        contents:
          - text: "Notes"
            href: lectures/day5/notes.qmd
          - text: "Slides"
            href: lectures/day5/slides.html
          - text: "Code"
            href: lectures/day5/shaders.qmd
      - text: "Download PDF"
        href: GPU-Accelerated-Mathematical-Illustration.pdf

format:
  html:
    theme:
      light: [cosmo, styles/website.scss]
      dark: [darkly, styles/website.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    link-external-newwindow: true
    smooth-scroll: true
