project:
  type: website
  output-dir: _site

website:
  title: "GPU-Accelerated Mathematical Illustration"
  repo-url: https://github.com/stevejtrettel/shader-course

  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Day 1: Pixels"
        contents:
          - text: "Notes"
            href: lectures/day1/notes.qmd
          - text: "Code"
            href: lectures/day1/shaders.qmd
          - text: "Homework"
            href: lectures/day1/homework.qmd
      - section: "Day 2: Fractals"
        contents:
          - text: "Notes"
            href: lectures/day2/notes.qmd
          - text: "Code"
            href: lectures/day2/shaders.qmd
          - text: "Homework"
            href: lectures/day2/homework.qmd
      - section: "Day 3: Tilings"
        contents:
          - text: "Notes"
            href: lectures/day3/notes.qmd
          - text: "Code"
            href: lectures/day3/shaders.qmd
      - section: "Day 4: Simulations"
        contents:
          - text: "Notes"
            href: lectures/day4/notes.qmd
          - text: "Code"
            href: lectures/day4/shaders.qmd
      - section: "Day 5: Rendering"
        contents:
          - text: "Notes"
            href: lectures/day5/notes.qmd
          - text: "Code"
            href: lectures/day5/shaders.qmd
      # - text: "Download PDF"
      #   href: GPU-Accelerated-Mathematical-Illustration.pdf
      - section: "Appendices"
        contents:
          - text: "GLSL Reference"
            href: appendices/glsl.qmd
          - text: "Coordinates"
            href: appendices/coordinates.qmd
          - text: "Color"
            href: appendices/color.qmd
          - text: "SDFs"
            href: appendices/sdfs.qmd
          - text: "Debugging"
            href: appendices/debug.qmd

format:
  html:
    theme:
      light: [cosmo, styles/website.scss]
      dark: [darkly, styles/website.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    link-external-newwindow: true
    smooth-scroll: true