# Netlify configuration for Quarto site

[build]
  publish = "_site"

[[plugins]]
  package = "@quarto/netlify-plugin-quarto"

  [plugins.inputs]
    cmd = "render && quarto render --profile print && cp _book/*.pdf _site/"
